// PocketAI-T M1a -- shared memory controller
//
// Byte-addressable 256 KiB SRAM (131072 x 16-bit) fronted by a fixed-priority
// arbiter for four request sources:
//   src0 = core0 instruction fetch
//   src1 = core0 data access
//   src2 = core1 instruction fetch   (reserved, unused in M1a)
//   src3 = core1 data access / AXI   (reserved, unused in M1a)
//
// The memory interface follows the ibex "immediate grant, 1-cycle latency"
// protocol used by ibex_top:
//   * a request (req) is granted (gnt) combinationally in the same cycle;
//   * the response (rvalid/rdata) is presented one cycle later.
// Because there are no outstanding requests, at most one request is granted
// per cycle and a single response-pipeline register is sufficient.
//
// Note on capacity: the M1a brief says "256 KiB (16Kx16, or two 32Kx16 banks)".
// 16K x 16-bit is actually 32 KiB, so we size the array to satisfy the 256 KiB
// requirement directly: 131072 x 16-bit = 256 KiB.

module pa_ram_ctrl
(
  input  logic        clk_i,
  input  logic        rst_ni,

  // source 0 -- core0 instruction
  input  logic        c0i_req_i,
  input  logic [31:0] c0i_addr_i,
  output logic        c0i_gnt_o,
  output logic        c0i_rvalid_o,
  output logic [31:0] c0i_rdata_o,

  // source 1 -- core0 data
  input  logic        c0d_req_i,
  input  logic        c0d_we_i,
  input  logic [3:0]  c0d_be_i,
  input  logic [31:0] c0d_addr_i,
  input  logic [31:0] c0d_wdata_i,
  output logic        c0d_gnt_o,
  output logic        c0d_rvalid_o,
  output logic [31:0] c0d_rdata_o,

  // source 2 -- core1 instruction (reserved)
  input  logic        c1i_req_i,
  input  logic [31:0] c1i_addr_i,
  output logic        c1i_gnt_o,
  output logic        c1i_rvalid_o,
  output logic [31:0] c1i_rdata_o,

  // source 3 -- core1 data / AXI (reserved)
  input  logic        c1d_req_i,
  input  logic        c1d_we_i,
  input  logic [3:0]  c1d_be_i,
  input  logic [31:0] c1d_addr_i,
  input  logic [31:0] c1d_wdata_i,
  output logic        c1d_gnt_o,
  output logic        c1d_rvalid_o,
  output logic [31:0] c1d_rdata_o
);

  localparam int AW      = 17;            // 131072 x 16-bit words
  localparam int NW      = (1 << AW);     // 131072 words == 256 KiB

  // ---------------------------------------------------------------------------
  // Storage
  // ---------------------------------------------------------------------------
  logic [15:0] mem [0:NW-1];

  // Preload from a hex file generated by sim/run.sh (only for the executable
  // simulation build; not used for --lint-only).
  `ifdef PA_MEM_INIT
    initial begin
      $readmemh("ram.mem", mem);
    end
  `endif

  // Byte lookup (in-bounds guarded) for assembling a 32-bit response.
  // The index is taken as a[17:1], so it is always in [0, NW-1]; out-of-range
  // addresses alias into the array (never used in M1a, but safe for indexing).
  function logic [7:0] ram_byte(input logic [31:0] a);
    logic [AW-1:0] idx;
    idx = a[17:1];
    return mem[idx][a[0] ? 15:8 : 7:0];
  endfunction

  function logic [31:0] ram_rdata(input logic [31:0] a);
    ram_rdata = {ram_byte(a + 32'd3),
                 ram_byte(a + 32'd2),
                 ram_byte(a + 32'd1),
                 ram_byte(a)};
  endfunction

  // ---------------------------------------------------------------------------
  // Fixed-priority arbiter: core0_instr > core0_data > core1_instr > core1_data
  // ---------------------------------------------------------------------------
  logic       granted;
  logic [1:0] widx;
  always_comb begin
    if      (c0i_req_i) begin granted = 1'b1; widx = 2'd0; end
    else if (c0d_req_i) begin granted = 1'b1; widx = 2'd1; end
    else if (c1i_req_i) begin granted = 1'b1; widx = 2'd2; end
    else if (c1d_req_i) begin granted = 1'b1; widx = 2'd3; end
    else                 begin granted = 1'b0; widx = 2'd0; end
  end

  // Mux the winning request.
  logic        w_we;
  logic [3:0]  w_be;
  logic [31:0] w_addr;
  logic [31:0] w_wdata;
  always_comb begin
    case (widx)
      2'd0: begin w_we=1'b0; w_be='0; w_addr=c0i_addr_i;  w_wdata=32'h0; end
      2'd1: begin w_we=c0d_we_i; w_be=c0d_be_i; w_addr=c0d_addr_i; w_wdata=c0d_wdata_i; end
      2'd2: begin w_we=1'b0; w_be='0; w_addr=c1i_addr_i;  w_wdata=32'h0; end
      2'd3: begin w_we=c1d_we_i; w_be=c1d_be_i; w_addr=c1d_addr_i; w_wdata=c1d_wdata_i; end
      default: begin w_we=1'b0; w_be='0; w_addr=32'h0; w_wdata=32'h0; end
    endcase
  end

  assign c0i_gnt_o = granted & (widx == 2'd0);
  assign c0d_gnt_o = granted & (widx == 2'd1);
  assign c1i_gnt_o = granted & (widx == 2'd2);
  assign c1d_gnt_o = granted & (widx == 2'd3);

  // ---------------------------------------------------------------------------
  // Memory + single-stage response pipeline
  // ---------------------------------------------------------------------------
  logic        resp_valid;
  logic [1:0]  resp_src;
  logic [31:0] resp_rdata;

  always_ff @(posedge clk_i or negedge rst_ni) begin
    if (!rst_ni) begin
      resp_valid <= 1'b0;
      resp_src   <= 2'd0;
    end else if (granted) begin
      // Byte-granular write. Only in-bounds bytes are committed.
      if (w_we) begin
        if (w_be[0]) mem[w_addr[17:1]][w_addr[0]?15:8:7:0] <= w_wdata[7:0];
        if (w_be[1]) mem[(w_addr+32'd1)[17:1]][(w_addr+32'd1)[0]?15:8:7:0] <= w_wdata[15:8];
        if (w_be[2]) mem[(w_addr+32'd2)[17:1]][(w_addr+32'd2)[0]?15:8:7:0] <= w_wdata[23:16];
        if (w_be[3]) mem[(w_addr+32'd3)[17:1]][(w_addr+32'd3)[0]?15:8:7:0] <= w_wdata[31:24];
      end
      resp_rdata <= ram_rdata(w_addr);
      resp_src   <= widx;
      resp_valid <= 1'b1;
    end else begin
      resp_valid <= 1'b0;
    end
  end

  assign c0i_rvalid_o = resp_valid & (resp_src == 2'd0);
  assign c0d_rvalid_o = resp_valid & (resp_src == 2'd1);
  assign c1i_rvalid_o = resp_valid & (resp_src == 2'd2);
  assign c1d_rvalid_o = resp_valid & (resp_src == 2'd3);

  assign c0i_rdata_o = resp_rdata;
  assign c0d_rdata_o = resp_rdata;
  assign c1i_rdata_o = resp_rdata;
  assign c1d_rdata_o = resp_rdata;

endmodule
